/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "rgb2gray" *)
(* src = "rgb2gray.sv:1.1-68.10" *)
module rgb2gray(clk_i, reset_i, valid_i, red_i, blue_i, green_i, ready_o, valid_o, gray_o, ready_i);
  (* src = "rgb2gray.sv:6.16-6.21" *)
  input [0:0] clk_i;
  wire [0:0] clk_i;
  (* src = "rgb2gray.sv:7.16-7.23" *)
  input [0:0] reset_i;
  wire [0:0] reset_i;
  (* src = "rgb2gray.sv:9.16-9.23" *)
  input [0:0] valid_i;
  wire [0:0] valid_i;
  (* src = "rgb2gray.sv:10.26-10.31" *)
  input [7:0] red_i;
  wire [7:0] red_i;
  (* src = "rgb2gray.sv:11.26-11.32" *)
  input [7:0] blue_i;
  wire [7:0] blue_i;
  (* src = "rgb2gray.sv:12.26-12.33" *)
  input [7:0] green_i;
  wire [7:0] green_i;
  (* src = "rgb2gray.sv:13.17-13.24" *)
  output [0:0] ready_o;
  wire [0:0] ready_o;
  (* src = "rgb2gray.sv:15.17-15.24" *)
  output [0:0] valid_o;
  wire [0:0] valid_o;
  (* src = "rgb2gray.sv:16.27-16.33" *)
  output [7:0] gray_o;
  wire [7:0] gray_o;
  (* src = "rgb2gray.sv:17.16-17.23" *)
  input [0:0] ready_i;
  wire [0:0] ready_i;
  wire _0_;
  wire _1_;
  wire _2_;
  (* fsm_encoding = "auto" *)
  (* src = "rgb2gray.sv:31.16-31.22" *)
  wire [15:0] blue_r;
  (* src = "rgb2gray.sv:28.14-28.22" *)
  wire [0:0] enable_w;
  (* fsm_encoding = "auto" *)
  (* src = "rgb2gray.sv:32.16-32.23" *)
  wire [15:0] green_r;
  (* fsm_encoding = "auto" *)
  (* src = "rgb2gray.sv:30.16-30.21" *)
  wire [15:0] red_r;
  (* src = "rgb2gray.sv:33.16-33.21" *)
  wire [15:0] sum_l;
  (* src = "rgb2gray.sv:29.15-29.22" *)
  reg [0:0] valid_r;
  assign enable_w = ready_o & valid_i;
  assign _0_ = valid_r & _1_;
  assign _1_ = ~ready_i;
  assign _2_ = ~_0_;
  (* \always_ff  = 32'd1 *)
  (* src = "rgb2gray.sv:38.3-45.6" *)
  always @(posedge clk_i)
    if (reset_i) valid_r <= 1'h0;
    else if (ready_o) valid_r <= enable_w;
  assign blue_r = 16'h0000;
  assign gray_o = 8'h00;
  assign green_r = 16'h0000;
  assign red_r = 16'h0000;
  assign sum_l = 16'h0000;
  assign valid_o = valid_r;
  assign ready_o = _2_;
endmodule
